set -U fish_color_normal d4d4d4
set -U fish_color_command dcdcaf
set -U fish_color_keyword b98dbc
set -U fish_color_quote c2977b
set -U fish_color_redirection d4d4d4
set -U fish_color_end d4d4d4
set -U fish_color_error --underline d86750
set -U fish_color_param aed8fb
set -U fish_color_valid_path --underline
# set -U fish_color_option 
set -U fish_color_comment 77955d
# set -U fish_color_selection
set -U fish_color_operator d4d4d4
set -U fish_color_escape d0bc84z
set -U fish_color_autosuggestion 6b6b6b
# set -u fish_color_cwd
# set -U fish_color_cwd_root
# set -U fish_color_user
# set -U fish_color_host
# set -U fish_color_host_remote
# set -U fish_color_status
set -U fish_color_cancel --reverse
# set -U fish_color_search_match
